# Creating a DTM

First importing all the standard python libraries.

In [1]:
import textmining
import shorttext
import pandas as pd
import numpy as np
import numpy.random as random
import matplotlib.pyplot as plt

Using TensorFlow backend.


Using the US Presidents speeches dataset to create a Document term matrix.

In [2]:
usprez = shorttext.data.inaugural()
docids=sorted(usprez.keys())
docsall=[]
for key in docids:
    s=''.join(usprez[key])
    docsall.append(s)

Next using the 'TermDocumentMatrix()' of the 'text mining' library to create the DTM.

In [3]:
tdm = textmining.TermDocumentMatrix()
for d in docsall:
    tdm.add_doc(d)
#tdm.write_csv('matrix.csv', cutoff=1)
c=0
ans=[]
for row in tdm.rows(cutoff=1):
    if(c==0):
        c=1
        continue
    ans.append(row)
print(ans)

[[3, 5, 71, 116, 1, 48, 2, 2, 1, 1, 1, 48, 1, 8, 2, 3, 12, 1, 8, 17, 1, 1, 6, 18, 36, 1, 4, 1, 20, 9, 2, 1, 15, 1, 2, 5, 1, 4, 3, 23, 1, 22, 5, 2, 2, 9, 2, 1, 3, 1, 2, 7, 14, 2, 1, 1, 1, 1, 31, 1, 1, 10, 2, 1, 14, 1, 1, 1, 2, 9, 8, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 11, 1, 1, 1, 1, 2, 1, 4, 1, 1, 1, 3, 1, 1, 1, 1, 3, 5, 2, 4, 1, 1, 3, 1, 1, 1, 3, 1, 1, 1, 2, 4, 23, 2, 1, 2, 1, 10, 1, 1, 3, 2, 1, 7, 5, 7, 1, 1, 1, 4, 2, 1, 1, 2, 1, 1, 1, 1, 1, 3, 1, 1, 1, 1, 2, 1, 5, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 12, 1, 1, 1, 1, 1, 10, 1, 1, 1, 4, 1, 1, 3, 2, 1, 3, 1, 3, 2, 5, 1, 6, 1, 1, 2, 1, 1, 1, 2, 2, 1, 1, 1, 1, 2, 2, 1, 1, 1, 1, 2, 1, 1, 2, 1, 1, 6, 1, 2, 3, 4, 4, 2, 8, 1, 2, 3, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 3, 1, 2, 3, 2, 4, 1, 2, 3, 2, 3, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 2, 3, 1, 2, 1, 1, 3, 1, 1, 2, 1, 1, 1, 1, 2, 2, 1, 1, 1, 1, 2, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 5, 1, 1, 3, 3, 1, 2, 1, 1, 2, 1, 1, 2, 1, 2, 2, 1, 1, 1, 1, 3, 2, 3, 1, 2, 2, 1, 1

Using numpy functions to find the dimensions and different features of the matrix.

In [4]:
a=np.array(ans)
print(a.shape)

(56, 8971)


In [5]:
#finding the transpose of the DTM, will be used later in the multiplication part
b=a.transpose()
print(b)

[[  3   1   3 ...   1   3   1]
 [  5   1   5 ...   9   6   1]
 [ 71  11 140 ...  58 116  82]
 ...
 [  0   0   0 ...   0   0   2]
 [  0   0   0 ...   0   0   1]
 [  0   0   0 ...   0   0   1]]


Now we are multiplying the DTM matrix and its tranpose and calculating the time taken by the operation.

In [6]:
#importing time library for calculating time
import time
time_starting=time.time()
d=np.matmul(b,a)
time_after=time.time()
print(time_after-time_starting)

7.102591276168823


# Matrix Multiplication using sampling

First calculating the square of the Frobenius norm of DTM.

In [7]:
frobenius_norm_square=np.sum(a**2)
frobenius_norm_square

6665205

Finding the probability using length square sampling.

In [8]:
probability_list=[]
sum=0;
for i in range(np.size(b,1)):
    q=np.array(b[:,i])
    probability_list.append((np.sum(q**2))/(1.0*frobenius_norm_square))
print(probability_list)

[0.0047036812821211055, 7.2465888145976e-05, 0.012931035129452132, 0.007018838880424533, 0.009182013156384537, 0.0038589960848916124, 0.0035460274665220348, 0.026163336311486294, 0.04340121571654585, 0.029748672396422916, 0.003516170920474314, 0.0038009333546380046, 0.02817347703483989, 0.21217426920852397, 0.057958457391783146, 0.003568832466518284, 0.021811332134570503, 0.018445944273281917, 0.02518467173927884, 0.0010764860195597884, 0.002765406315334637, 0.004197470295362258, 0.018412787003550528, 0.026631739008777675, 0.009916874274684725, 0.04463478617686928, 0.010129620919386576, 0.0390915208159389, 0.011987478254607322, 0.0020776555259740697, 0.07773414321089898, 0.005959756676651356, 0.005160681479414362, 0.02071654210185583, 0.031964808284216314, 0.03193405154080032, 0.007213131479076788, 0.006178204571352269, 0.004757243025533348, 0.0006676463814691371, 0.010185883254903638, 0.013803476412203376, 0.00623506703844818, 0.0033896931902319583, 0.004003327729604716, 0.00857092917

Considering only 1 independant trial.

In [16]:
s=1
rows=np.size(b,1)
#index variable gives us a random number(k) which is the column number of b and corresponding row of a.
index=random.choice(rows,s,probability_list)
print(index)

[46]


Multiplication of the kth column of b and kth row of a

In [58]:
#Using the time library for finding the time taken to calculate this approx matrix
p=np.array(probability_list)
t=p[index]
const=1.0/t[0]
b_kth_column=np.matrix(b[:,index])*const
a_kth_row=np.matrix(a[index])
time_start=time.time()
X=np.dot(b_kth_column[:,None],a_kth_row[None,:])
time_end=time.time()
print(X)
print(X.shape)
print("Time Taken: " +str(time_end-time_start))

[[1.74454405e+02 1.74454405e+02 1.18628995e+04 ... 0.00000000e+00
  0.00000000e+00 0.00000000e+00]
 [1.74454405e+02 1.74454405e+02 1.18628995e+04 ... 0.00000000e+00
  0.00000000e+00 0.00000000e+00]
 [1.18628995e+04 1.18628995e+04 8.06677169e+05 ... 0.00000000e+00
  0.00000000e+00 0.00000000e+00]
 ...
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
  0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
  0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
  0.00000000e+00 0.00000000e+00]]
(8971, 8971)
Time Taken: 2.2059836387634277


Considering Multiple trials.

In [35]:
#suppose s=50
s=50
rows=np.size(b,1)
all_index=random.choice(rows,s,probability_list)
print(all_index)

56
[45 26 32 42 47 34 20 55 25 42 44 14 23  2 49  8 13 17 12 17 43 14 43  3
  1 33 43 10  3 46  4 28 46 33 35  9 35 30 55 22 53 52  5 45  3  3 18 25
 17 50]


In [37]:
#Creating a zero matrix
X=np.zeros((np.size(b,0),np.size(b,0)))

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [57]:
#though the multiple trials method takes a lot more time than the single trials method but it is more accurate
for i in range(0,s):
    t=p[all_index[i]]
    a1=np.array(b[:,all_index[i]])*(1.0/t)
    b1=np.array(a[all_index[i]])
    y=np.dot(a1[:,None],b1[None,:])
    X=np.add(X,y)
X=X*(1.0/s)
print(X)

[[1.77559895e+03 2.01340269e+03 3.41155582e+04 ... 7.96154329e+00
  3.98077164e+00 3.98077164e+00]
 [2.01340269e+03 2.90442052e+03 4.79419029e+04 ... 7.96154329e+00
  3.98077164e+00 3.98077164e+00]
 [3.41155582e+04 4.79419029e+04 1.21534228e+06 ... 6.52846549e+02
  3.26423275e+02 3.26423275e+02]
 ...
 [7.96154329e+00 7.96154329e+00 6.52846549e+02 ... 1.59230866e+01
  7.96154329e+00 7.96154329e+00]
 [3.98077164e+00 3.98077164e+00 3.26423275e+02 ... 7.96154329e+00
  3.98077164e+00 3.98077164e+00]
 [3.98077164e+00 3.98077164e+00 3.26423275e+02 ... 7.96154329e+00
  3.98077164e+00 3.98077164e+00]]
